spring.application.name=demo
server.port=8080

pokemon.api.base-url=https://pokeapi.co/api/v2/
pokemon.api.timeout=5s
pokemon.cache.maximum-size=100
pokemon.cache.expire-after-write=10m

logging.level.com.example.demo=INFO
